openapi: 3.0.0
info:
  description: API for SOMESimplify
  version: 1.0.0
  title: SOMESimplify API
  contact:
    name: Johan Svartdal
    url: https://www.somesimplify.com
    email: johan.svartdal30@gmail.com
paths:
  # authApi
  '/auth/register':
    $ref: './paths/auth/register.yaml'
  '/auth/login':
    $ref: './paths/auth/login.yaml'
  '/auth/logout':
    $ref: './paths/auth/logout.yaml'

  # userApi
  '/user':
    $ref: './paths/user/user.yaml'

  # tenantApi
  '/tenants':
    $ref: './paths/tenant/tenants.yaml'
  '/tenants/{id}':
    $ref: './paths/tenant/tenant.yaml'

  # imageApi
  '/images':
    $ref: './paths/image/images.yaml'
  '/images/{id}':
    $ref: './paths/image/image.yaml'

  # postApi
  '/posts':
    $ref: './paths/post/posts.yaml'
  '/posts/{id}':
    $ref: './paths/post/post.yaml'
  '/posts/suggested-publish-date':
    $ref: './paths/post/suggested-publish-date.yaml'

  # instagramApi
  '/instagram/connect':
    $ref: './paths/instagram/connect.yaml'
  '/instagram/oauth/callback':
    $ref: './paths/instagram/callback.yaml'
  '/instagram/connection':
    $ref: './paths/instagram/connection.yaml'